import React from 'react';
import {mcpRequest,McpCredentials} from '../api/client';
const ops:Record<string,{method:string;path:string;sample:object}>={
 context:{method:'GET',path:'/context',sample:{}},
 subject:{method:'POST',path:'/subjects',sample:{subject:'replace-with-human-jwt-sub',groups:['employees'],active:true,sourceVersion:1}},
 resource:{method:'POST',path:'/resources',sample:{resourceId:'demo-folder',kind:'FOLDER',title:'Client folder',ownerSubject:'source-admin',sourceVersion:1,acl:[{principalKind:'GROUP',principalId:'employees',permission:'READ',effect:'ALLOW'},{principalKind:'GROUP',principalId:'employees',permission:'SEARCH',effect:'ALLOW'}],chunks:[]}},
 state:{method:'GET',path:'/source-state',sample:{}},
 checkpoint:{method:'POST',path:'/source-state',sample:{ready:true,expectedAclVersion:1}},
 delegate:{method:'POST',path:'/sessions',sample:{aiSubject:'client:replace-with-ai-client'}},
 read:{method:'POST',path:'/retrieve',sample:{resourceId:'demo-folder'}},
 search:{method:'POST',path:'/search',sample:{query:'Project'}},
 mcp:{method:'POST',path:'/mcp',sample:{jsonrpc:'2.0',id:'client-demo',method:'tools/call',params:{name:'readDocument',arguments:{resourceId:'demo-folder'}}}},
 calls:{method:'GET',path:'/calls',sample:{}},
};
export default function RetrievalClientConsole({workspace}:{workspace:string}){
 const [credentials,setCredentials]=React.useState<McpCredentials>({mode:'bearer'}),[operation,setOperation]=React.useState(''),[json,setJson]=React.useState('{}'),[session,setSession]=React.useState(''),[result,setResult]=React.useState<any>(null),[identity,setIdentity]=React.useState<any>(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
 React.useEffect(()=>{setCredentials({mode:'bearer'});setSession('');setResult(null);setIdentity(null);setError('');setOperation('');setJson('{}')},[workspace]);
 const send=async()=>{if(!workspace||!operation)return;setBusy(true);setError('');setResult(null);try{const op=ops[operation];const payload=op.method==='GET'?undefined:JSON.parse(json);const headers:Record<string,string>={'X-Workspace-Id':workspace};if(operation==='mcp'){headers['MCP-Protocol-Version']='2025-06-18';if(session)headers['X-ZT-Delegation']=session}else if((credentials.mode==='service'||identity?.actorType==='AI_AGENT')&&['read','search'].includes(operation)){if(!session)throw Error('Human-issued AI session required');payload.sessionId=session}const response=await mcpRequest('/v1/integrations/retrieval'+op.path,op.method,payload,credentials,headers);setResult(response);if(operation==='context')setIdentity(response);if(response?.sessionId)setSession(response.sessionId)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <section className="panel"><h3>Client contract console — any registered source</h3><p>Use the selected workspace and the caller’s own credential. The administrator credential used for policy management is not used for these calls. Source sync requires the registered connector; human delegation requires HUMAN JWT; AI retrieval requires its own credential and human-issued session.</p>{error&&<div className="error-banner" role="alert">{error}</div>}<label>Actor credential<select disabled={busy} value={credentials.mode} onChange={e=>{setCredentials({mode:e.target.value as McpCredentials['mode']});setIdentity(null);setResult(null)}}><option value="bearer">OIDC JWT — connector / human / AI</option><option value="service">Registered AI service client</option></select></label>{credentials.mode==='service'&&<label>AI client ID<input disabled={busy} value={credentials.clientId||''} onChange={e=>{setCredentials({...credentials,clientId:e.target.value});setIdentity(null);setResult(null)}}/></label>}<label>{credentials.mode==='bearer'?'Bearer token':'AI secret'}<input type="password" autoComplete="off" disabled={busy} value={credentials.secret||''} onChange={e=>{setCredentials({...credentials,secret:e.target.value});setIdentity(null);setResult(null)}}/></label><label>Operation<select disabled={busy} value={operation} onChange={e=>{setOperation(e.target.value);setJson(JSON.stringify(ops[e.target.value]?.sample||{},null,2));setResult(null)}}><option value="">Select operation</option>{Object.keys(ops).map(key=><option key={key} value={key}>{key} — {ops[key].method} {ops[key].path}</option>)}</select></label><label>AI delegation handle — trusted application state<input disabled={busy} value={session} onChange={e=>setSession(e.target.value)}/></label>{operation&&ops[operation].method!=='GET'&&<label>Request JSON<textarea rows={12} disabled={busy} value={json} onChange={e=>setJson(e.target.value)}/></label>}<button disabled={busy||!workspace||!operation||!credentials.secret?.trim()} onClick={send}>{busy?'Sending…':'Send as client actor'}</button><button disabled={busy} onClick={()=>{setCredentials({mode:'bearer'});setSession('');setIdentity(null);setResult(null)}}>Clear credentials / session / response</button>{result&&<pre className="json">{JSON.stringify(result,null,2)}</pre>}<p>Credentials stay in page memory and clear on workspace change. Read the actual actor with context before syncing. Examples are templates: replace IDs/groups and increase sourceVersion on updates. Copy the source-state ACL version into checkpoint after a complete snapshot. JWT AI requests also need a matching retrieval_session_id claim.</p></section>;
}

