apiVersion: v1
kind: ConfigMap
metadata:
  name: zt-security-config
  namespace: zt-security
data:
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75 -XX:+ExitOnOutOfMemoryError"
---
apiVersion: v1
kind: Secret
metadata:
  name: zt-security-secrets
  namespace: zt-security
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_ME"
  DATABASE_USERNAME: "REPLACE_ME"
  DATABASE_PASSWORD: "REPLACE_ME"
