package com.zt.security.stitch;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.zt.security.common.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import org.springframework.beans.factory.annotation.Value;
import java.time.*;
import java.sql.Timestamp;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

@Service @Transactional @ConditionalOnProperty(name="zt.stitch.enabled",havingValue="true")
public class StitchIntegrationService {
    private static final String SCOPE="tenant_id=:tenant AND workspace_id=:workspace";
    private final NamedParameterJdbcTemplate jdbc;private final TenantSession tenants;private final WorkspaceSession workspaces;
    private final StitchIdentity identities;private final ObjectMapper mapper;
    @Value("${zt.stitch.session-ttl-seconds:300}") private int sessionTtl;
    @Value("${zt.stitch.max-source-age-seconds:120}") private int maxSourceAge;
    public StitchIntegrationService(NamedParameterJdbcTemplate jdbc,TenantSession tenants,WorkspaceSession workspaces,StitchIdentity identities,ObjectMapper mapper){this.jdbc=jdbc;this.tenants=tenants;this.workspaces=workspaces;this.identities=identities;this.mapper=mapper;}
    private MapSqlParameterSource scope(UUID t,UUID w){
        tenants.set(t);workspaces.set(w);var p=new MapSqlParameterSource().addValue("tenant",t).addValue("workspace",w);
        if(!Integer.valueOf(1).equals(jdbc.queryForObject("SELECT count(*) FROM workspaces WHERE tenant_id=:tenant AND id=:workspace",p,Integer.class)))throw new AccessDeniedException("Workspace unavailable");
        jdbc.queryForObject("SELECT pg_advisory_xact_lock(hashtextextended(:key,0))",Map.of("key","stitch-integration:"+t+":"+w),Object.class);
        jdbc.update("INSERT INTO stitch_integration_scopes(tenant_id,workspace_id) VALUES(:tenant,:workspace) ON CONFLICT DO NOTHING",p);return p;
    }
    private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception ex){throw new IllegalArgumentException("Invalid connector JSON");}}
    private long version(MapSqlParameterSource p){return Objects.requireNonNull(jdbc.queryForObject("SELECT acl_version FROM stitch_integration_scopes WHERE "+SCOPE,p,Long.class));}
    private void sourceDirty(MapSqlParameterSource p){jdbc.update("UPDATE stitch_integration_scopes SET source_ready=false WHERE "+SCOPE,p);}
    private void sourceFresh(MapSqlParameterSource p){if(jdbc.queryForObject("SELECT count(*) FROM stitch_integration_scopes WHERE "+SCOPE+" AND source_ready=true AND source_refreshed_at>now()-:age*interval '1 second'",new MapSqlParameterSource(p.getValues()).addValue("age",Math.max(30,Math.min(3600,maxSourceAge))),Integer.class)!=1)throw new AccessDeniedException("Source ACL snapshot is stale or incomplete; connector checkpoint required");}
    public Object state(UUID t,UUID w,Authentication auth){identities.connector(auth,t,w);var p=scope(t,w);var r=jdbc.queryForList("SELECT acl_version,source_ready,source_refreshed_at FROM stitch_integration_scopes WHERE "+SCOPE,p).get(0);return r;}
    public Object checkpoint(UUID t,UUID w,StitchContracts.Checkpoint x,Authentication auth){identities.connector(auth,t,w);var p=scope(t,w).addValue("expected",x.expectedAclVersion()).addValue("ready",x.ready());if(jdbc.update("UPDATE stitch_integration_scopes SET source_ready=:ready,source_refreshed_at=CASE WHEN :ready THEN now() ELSE source_refreshed_at END WHERE "+SCOPE+" AND acl_version=:expected",p)!=1)throw new ResponseStatusException(HttpStatus.CONFLICT,"ACL changed before source checkpoint; re-read source state");return Map.of("ready",x.ready(),"aclVersion",version(p));}
    private void invalidate(MapSqlParameterSource p){jdbc.update("UPDATE stitch_integration_scopes SET acl_version=acl_version+1 WHERE "+SCOPE,p);jdbc.update("DELETE FROM stitch_retrieval_cache WHERE "+SCOPE,p);}
    private Map<String,Map<String,Object>> resources(MapSqlParameterSource p){var rows=jdbc.queryForList("SELECT resource_id,parent_id,kind,owner_subject,ai_access,deleted,purge_after,source_version FROM stitch_resources WHERE "+SCOPE+" LIMIT 5001",p);if(rows.size()>5000)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Connector scope exceeds bounded adapter capacity");Map<String,Map<String,Object>> map=new HashMap<>();for(var x:rows)map.put((String)x.get("resource_id"),x);return map;}
    private Map<String,List<Map<String,Object>>> grants(MapSqlParameterSource p){var rows=jdbc.queryForList("SELECT resource_id,principal_kind,principal_id,permission,effect FROM stitch_resource_acl WHERE "+SCOPE+" LIMIT 50001",p);if(rows.size()>50000)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"ACL scope exceeds bounded capacity");Map<String,List<Map<String,Object>>> result=new HashMap<>();for(var r:rows)result.computeIfAbsent((String)r.get("resource_id"),key->new ArrayList<>()).add(r);return result;}
    public Object sync(UUID t,UUID w,StitchContracts.Resource x,Authentication auth){
        var actor=identities.connector(auth,t,w);var p=scope(t,w).addValue("id",x.resourceId());var all=resources(p);var old=all.get(x.resourceId());
        if(old!=null&&((Number)old.get("source_version")).longValue()>=x.sourceVersion())throw new ResponseStatusException(HttpStatus.CONFLICT,"Source version must increase");
        if(old==null&&all.size()>=5000)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Resource capacity reached; shard the source scope");
        if(old!=null&&!x.kind().equals(old.get("kind"))&&all.values().stream().anyMatch(r->x.resourceId().equals(r.get("parent_id"))))throw new IllegalArgumentException("Cannot change kind of an existing parent resource");
        if(x.purgeAfter()!=null&&!x.purgeAfter().isAfter(Instant.now()))throw new IllegalArgumentException("Use deletion for expired resources");
        String parent=x.parentId();Set<String> seen=new HashSet<>();seen.add(x.resourceId());int depth=0;
        while(parent!=null){if(!seen.add(parent)||++depth>64)throw new IllegalArgumentException("Invalid resource ancestry");var r=all.get(parent);if(r==null||Boolean.TRUE.equals(r.get("deleted")))throw new IllegalArgumentException("Sync active parent before child");parent=(String)r.get("parent_id");}
        if(x.parentId()!=null){String parentKind=(String)all.get(x.parentId()).get("kind");boolean allowed=switch(x.kind()){case "FOLDER"->"FOLDER".equals(parentKind);case "CHANNEL"->"FOLDER".equals(parentKind);case "FILE"->List.of("FOLDER","CHANNEL").contains(parentKind);case "MESSAGE"->"CHANNEL".equals(parentKind);case "ATTACHMENT"->List.of("FILE","MESSAGE").contains(parentKind);default->false;};if(!allowed)throw new IllegalArgumentException("Invalid parent kind");}else if(List.of("ATTACHMENT","MESSAGE").contains(x.kind()))throw new IllegalArgumentException("Parent required for attachment/message");
        Set<String> unique=new HashSet<>();for(var g:x.acl())if(!unique.add(g.principalKind()+":"+g.principalId()+":"+g.permission()))throw new IllegalArgumentException("Duplicate ACL entry");
        if(jdbc.queryForObject("SELECT count(*) FROM stitch_resource_acl WHERE "+SCOPE+" AND resource_id<>:id",p,Long.class)+x.acl().size()>50000)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"ACL capacity reached; shard the source scope");
        int total=x.content()==null?0:x.content().length();for(var c:x.chunks()){total+=c.content().length();vector(c.embedding());}if(total>1048576)throw new IllegalArgumentException("Connector content exceeds scope ingestion limit");
        byte[] blob=null;if(x.fileBase64()!=null){if(!List.of("FILE","ATTACHMENT").contains(x.kind()))throw new IllegalArgumentException("Binary payload is only valid for FILE/ATTACHMENT");try{blob=Base64.getDecoder().decode(x.fileBase64());}catch(IllegalArgumentException ex){throw new IllegalArgumentException("Invalid file Base64");}if(blob.length>1048576)throw new IllegalArgumentException("File limit is 1 MiB");}
        p.addValue("parent",x.parentId()).addValue("kind",x.kind()).addValue("title",x.title()).addValue("owner",x.ownerSubject()).addValue("access",x.aiAccess()).addValue("sourceVersion",x.sourceVersion()).addValue("purge",x.purgeAfter()==null?null:Timestamp.from(x.purgeAfter())).addValue("content",x.content()==null?"":x.content());
        jdbc.update("INSERT INTO stitch_resources(tenant_id,workspace_id,resource_id,parent_id,kind,title,owner_subject,ai_access,source_version,purge_after,content) VALUES(:tenant,:workspace,:id,:parent,:kind,:title,:owner,:access,:sourceVersion,:purge,:content) ON CONFLICT(tenant_id,workspace_id,resource_id) DO UPDATE SET parent_id=EXCLUDED.parent_id,kind=EXCLUDED.kind,title=EXCLUDED.title,owner_subject=EXCLUDED.owner_subject,ai_access=EXCLUDED.ai_access,source_version=EXCLUDED.source_version,purge_after=EXCLUDED.purge_after,content=EXCLUDED.content,deleted=false",p);
        jdbc.update("DELETE FROM stitch_resource_acl WHERE "+SCOPE+" AND resource_id=:id",p);for(var g:x.acl())jdbc.update("INSERT INTO stitch_resource_acl(tenant_id,workspace_id,resource_id,principal_kind,principal_id,permission,effect) VALUES(:tenant,:workspace,:id,:kind,:principal,:permission,:effect)",new MapSqlParameterSource(p.getValues()).addValue("kind",g.principalKind()).addValue("principal",g.principalId()).addValue("permission",g.permission()).addValue("effect",g.effect()));
        jdbc.update("DELETE FROM stitch_rag_chunks WHERE "+SCOPE+" AND resource_id=:id",p);int n=0;var chunks=x.chunks().isEmpty()&&x.content()!=null&&!x.content().isBlank()?List.of(new StitchContracts.Chunk(x.content(),null)):x.chunks();for(var c:chunks)jdbc.update("INSERT INTO stitch_rag_chunks(tenant_id,workspace_id,resource_id,chunk_id,content,embedding) VALUES(:tenant,:workspace,:id,:chunk,:text,CAST(:embedding AS jsonb))",new MapSqlParameterSource(p.getValues()).addValue("chunk",n++).addValue("text",c.content()).addValue("embedding",c.embedding()==null?null:json(c.embedding())));
        jdbc.update("DELETE FROM stitch_file_blobs WHERE "+SCOPE+" AND resource_id=:id",p);if(blob!=null)jdbc.update("INSERT INTO stitch_file_blobs(tenant_id,workspace_id,resource_id,data) VALUES(:tenant,:workspace,:id,:blob)",new MapSqlParameterSource(p.getValues()).addValue("blob",blob));
        invalidate(p);sourceDirty(p);revokeDisclosures(p,"ACL_OR_CONTENT_CHANGED");audit(p,actor.subject(),"sync",x.resourceId(),"ALLOW",0);return Map.of("resourceId",x.resourceId(),"sourceVersion",x.sourceVersion(),"aclVersion",version(p),"chunks",n);
    }
    private record Caller(String subject,String human,Set<String> groups,String ai,UUID session){}
    private void stillValid(UUID t,UUID w,Authentication auth,Caller c,MapSqlParameterSource p){identities.resolve(auth,t,w);sourceFresh(p);if(c.session()!=null&&jdbc.queryForObject("SELECT count(*) FROM stitch_ai_sessions WHERE "+SCOPE+" AND id=:session AND ai_subject=:ai AND revoked=false AND expires_at>now()",new MapSqlParameterSource(p.getValues()).addValue("session",c.session()).addValue("ai",c.ai()),Integer.class)!=1)throw new AccessDeniedException("Delegation expired during retrieval");}
    public Object subjects(UUID t,UUID w,StitchContracts.Subject x,Authentication auth){var a=identities.connector(auth,t,w);var p=scope(t,w).addValue("subject",x.subject()).addValue("groups",json(x.groups())).addValue("active",x.active()).addValue("sourceVersion",x.sourceVersion());var old=jdbc.queryForList("SELECT source_version FROM stitch_subjects WHERE "+SCOPE+" AND subject=:subject",p);if(!old.isEmpty()&&((Number)old.get(0).get("source_version")).longValue()>=x.sourceVersion())throw new ResponseStatusException(HttpStatus.CONFLICT,"Subject source version must increase");jdbc.update("INSERT INTO stitch_subjects(tenant_id,workspace_id,subject,groups_json,active,source_version) VALUES(:tenant,:workspace,:subject,CAST(:groups AS jsonb),:active,:sourceVersion) ON CONFLICT(tenant_id,workspace_id,subject) DO UPDATE SET groups_json=EXCLUDED.groups_json,active=EXCLUDED.active,source_version=EXCLUDED.source_version",p);invalidate(p);sourceDirty(p);revokeDisclosures(p,"SUBJECT_MEMBERSHIP_CHANGED");if(!x.active())jdbc.update("UPDATE stitch_ai_sessions SET revoked=true WHERE "+SCOPE+" AND human_subject=:subject",p);audit(p,a.subject(),"syncSubject",null,"ALLOW",0);return Map.of("subject",x.subject(),"sourceVersion",x.sourceVersion(),"aclVersion",version(p));}
    private Set<String> liveGroups(MapSqlParameterSource p,String subject,Set<String> asserted){var rows=jdbc.queryForList("SELECT groups_json,active FROM stitch_subjects WHERE "+SCOPE+" AND subject=:human",new MapSqlParameterSource(p.getValues()).addValue("human",subject));if(rows.size()!=1||!Boolean.TRUE.equals(rows.get(0).get("active")))throw new AccessDeniedException("User is not provisioned or is disabled in source ACL directory");try{Set<String> groups=mapper.readValue(rows.get(0).get("groups_json").toString(),new TypeReference<Set<String>>(){});groups.retainAll(asserted);return groups;}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new AccessDeniedException("Invalid source membership");}}
    private Caller caller(UUID t,UUID w,Authentication auth,UUID session,MapSqlParameterSource p){
        var a=identities.resolve(auth,t,w);sourceFresh(p);if("HUMAN".equals(a.type())){if(session!=null)throw new IllegalArgumentException("Human retrieval must not use an AI session");return new Caller(a.subject(),a.subject(),liveGroups(p,a.subject(),a.groups()),null,null);}
        if(!"AI_AGENT".equals(a.type())||session==null)throw new AccessDeniedException("AI retrieval requires human-issued delegation session");
        if(auth instanceof org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken jwt&&!session.toString().equals(jwt.getToken().getClaimAsString("stitch_session_id")))throw new AccessDeniedException("AI JWT must be bound to stitch_session_id");
        var rows=jdbc.queryForList("SELECT human_subject,groups_json,ai_subject,expires_at,revoked FROM stitch_ai_sessions WHERE "+SCOPE+" AND id=:session",new MapSqlParameterSource(p.getValues()).addValue("session",session));
        if(rows.size()!=1)throw new AccessDeniedException("Session unavailable");var r=rows.get(0);
        if(!a.subject().equals(r.get("ai_subject"))||Boolean.TRUE.equals(r.get("revoked"))||!((Timestamp)r.get("expires_at")).toInstant().isAfter(Instant.now()))throw new AccessDeniedException("Expired, revoked or mismatched session");
        try{String human=(String)r.get("human_subject");Set<String> asserted=mapper.readValue(r.get("groups_json").toString(),new TypeReference<Set<String>>(){});return new Caller(a.subject(),human,liveGroups(p,human,asserted),a.subject(),session);}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new AccessDeniedException("Invalid delegated claims");}
    }
    public Object delegate(UUID t,UUID w,String ai,Authentication auth){var a=identities.resolve(auth,t,w);if(!"HUMAN".equals(a.type()))throw new AccessDeniedException("Only an authenticated human can delegate");var p=scope(t,w);sourceFresh(p);Set<String> delegatedGroups=liveGroups(p,a.subject(),a.groups());if(jdbc.queryForObject("SELECT count(*) FROM stitch_ai_sessions WHERE "+SCOPE+" AND human_subject=:human AND revoked=false AND expires_at>now()",new MapSqlParameterSource(p.getValues()).addValue("human",a.subject()),Integer.class)>=20)throw new ResponseStatusException(HttpStatus.TOO_MANY_REQUESTS,"Maximum active delegations reached");UUID id=UUID.randomUUID();Instant expires=Instant.now().plusSeconds(Math.max(30,Math.min(900,sessionTtl)));if(a.expiresAt().isBefore(expires))expires=a.expiresAt();jdbc.update("INSERT INTO stitch_ai_sessions(id,tenant_id,workspace_id,human_subject,human_jti,groups_json,ai_subject,expires_at) VALUES(:id,:tenant,:workspace,:human,:jti,CAST(:groups AS jsonb),:ai,:expires)",new MapSqlParameterSource(p.getValues()).addValue("id",id).addValue("human",a.subject()).addValue("jti",a.jti()).addValue("groups",json(delegatedGroups)).addValue("ai",ai).addValue("expires",Timestamp.from(expires)));audit(p,a.subject(),"delegate",null,"ALLOW",0);return Map.of("sessionId",id,"humanSubject",a.subject(),"aiSubject",ai,"expiresAt",expires);}
    public Object revoke(UUID t,UUID w,UUID id,Authentication auth){var a=identities.resolve(auth,t,w);var p=scope(t,w).addValue("session",id).addValue("human",a.subject());if(!a.sync()&&!"HUMAN".equals(a.type()))throw new AccessDeniedException("Human owner or connector required");int changed=jdbc.update("UPDATE stitch_ai_sessions SET revoked=true WHERE "+SCOPE+" AND id=:session"+(a.sync()?"":" AND human_subject=:human"),p);if(changed==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Session unavailable");invalidate(p);revokeDisclosures(p,"SESSION_REVOKED");audit(p,a.subject(),"revokeSession",null,"ALLOW",0);return Map.of("revoked",id);}
    public Object retrieve(UUID t,UUID w,StitchContracts.Retrieve x,Authentication auth){var p=scope(t,w);var c=caller(t,w,auth,x.sessionId(),p);var all=resources(p);var acl=grants(p);boolean allowed=StitchAccess.permits(x.resourceId(),"READ",c.human(),c.groups(),c.ai(),all,acl);if(!allowed){audit(p,c.subject(),"retrieve",x.resourceId(),"DENY",0);return Map.of("decision","DENY","results",List.of(),"aclVersion",version(p));}
        var rows=jdbc.queryForList("SELECT resource_id,kind,title,content,source_version FROM stitch_resources WHERE "+SCOPE+" AND resource_id=:id AND deleted=false",new MapSqlParameterSource(p.getValues()).addValue("id",x.resourceId()));stillValid(t,w,auth,c,p);if(!StitchAccess.permits(x.resourceId(),"READ",c.human(),c.groups(),c.ai(),all,acl)){audit(p,c.subject(),"retrieve",x.resourceId(),"DENY",0);return Map.of("decision","DENY","results",List.of(),"aclVersion",version(p));}disclose(p,c,List.of(x.resourceId()));audit(p,c.subject(),"retrieve",x.resourceId(),"ALLOW",rows.size());return Map.of("decision","ALLOW","results",rows,"aclVersion",version(p));}
    public Object search(UUID t,UUID w,StitchContracts.Search x,Authentication auth){
        vector(x.queryEmbedding());var p=scope(t,w);var c=caller(t,w,auth,x.sessionId(),p);var all=resources(p);var acl=grants(p);List<String> allowed=all.keySet().stream().filter(id->StitchAccess.permits(id,"SEARCH",c.human(),c.groups(),c.ai(),all,acl)&&StitchAccess.permits(id,"READ",c.human(),c.groups(),c.ai(),all,acl)).sorted().toList();
        if(allowed.isEmpty()){audit(p,c.subject(),"search",null,"ALLOW",0);return Map.of("decision","ALLOW","results",List.of(),"aclVersion",version(p));}
        String key=hash(json(List.of(c.subject(),c.human(),new TreeSet<>(c.groups()),c.session()==null?"":c.session().toString(),x.query(),x.queryEmbedding()==null?List.of():x.queryEmbedding())));long revision=version(p);var q=new MapSqlParameterSource(p.getValues()).addValue("key",key).addValue("version",revision).addValue("ids",allowed).addValue("query",x.query());List<Map<String,Object>> rows;
        var cached=x.queryEmbedding()!=null&&!x.queryEmbedding().isEmpty()?List.<Map<String,Object>>of():jdbc.queryForList("SELECT result_ids FROM stitch_retrieval_cache WHERE "+SCOPE+" AND cache_key=:key AND acl_version=:version AND expires_at>now()",q);
        List<String> ids=null;if(!cached.isEmpty())try{ids=mapper.readValue(cached.get(0).get("result_ids").toString(),new TypeReference<List<String>>(){});}catch(com.fasterxml.jackson.core.JsonProcessingException ignored){ids=null;}
        if(ids!=null){var valid=ids.stream().filter(k->allowed.contains(k.substring(0,k.lastIndexOf('#')))).toList();rows=valid.isEmpty()?List.of():jdbc.queryForList("SELECT resource_id,chunk_id,content FROM stitch_rag_chunks WHERE "+SCOPE+" AND resource_id IN (:ids) AND (resource_id||'#'||chunk_id::text) IN (:keys) ORDER BY resource_id,chunk_id",q.addValue("keys",valid));rows=new ArrayList<>(rows);rows.sort(Comparator.comparingInt(r->valid.indexOf(r.get("resource_id")+"#"+r.get("chunk_id"))));}
        else if(x.queryEmbedding()==null||x.queryEmbedding().isEmpty())rows=jdbc.queryForList("SELECT resource_id,chunk_id,content FROM stitch_rag_chunks WHERE "+SCOPE+" AND resource_id IN (:ids) AND search_vector @@ plainto_tsquery('simple',:query) ORDER BY ts_rank(search_vector,plainto_tsquery('simple',:query)) DESC,resource_id,chunk_id LIMIT 20",q);
        else{
            rows=jdbc.queryForList("SELECT resource_id,chunk_id,content,embedding FROM stitch_rag_chunks WHERE "+SCOPE+" AND resource_id IN (:ids) AND embedding IS NOT NULL ORDER BY resource_id,chunk_id LIMIT 5001",q);if(rows.size()>5000)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Authorized vector scope exceeds bounded capacity");List<Map<String,Object>> ranked=new ArrayList<>();for(var row:rows){try{List<Double> v=mapper.readValue(row.get("embedding").toString(),new TypeReference<List<Double>>(){});if(v.size()!=x.queryEmbedding().size())continue;var r=new LinkedHashMap<>(row);r.remove("embedding");r.put("score",cosine(v,x.queryEmbedding()));ranked.add(r);}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new IllegalStateException("Invalid stored embedding");}}ranked.sort(Comparator.comparingDouble((Map<String,Object> r)->((Number)r.get("score")).doubleValue()).reversed());rows=ranked.stream().limit(20).toList();
        }
        stillValid(t,w,auth,c,p);rows=rows.stream().filter(r->StitchAccess.permits((String)r.get("resource_id"),"READ",c.human(),c.groups(),c.ai(),all,acl)&&StitchAccess.permits((String)r.get("resource_id"),"SEARCH",c.human(),c.groups(),c.ai(),all,acl)).toList();
        if(ids==null&&(x.queryEmbedding()==null||x.queryEmbedding().isEmpty()))jdbc.update("INSERT INTO stitch_retrieval_cache(tenant_id,workspace_id,cache_key,acl_version,result_ids,expires_at) VALUES(:tenant,:workspace,:key,:version,CAST(:results AS jsonb),now()+interval '60 seconds') ON CONFLICT(tenant_id,workspace_id,cache_key) DO UPDATE SET acl_version=EXCLUDED.acl_version,result_ids=EXCLUDED.result_ids,expires_at=EXCLUDED.expires_at",q.addValue("results",json(rows.stream().map(r->r.get("resource_id")+"#"+r.get("chunk_id")).toList())));
        disclose(p,c,rows.stream().map(r->(String)r.get("resource_id")).distinct().toList());audit(p,c.subject(),"search",null,"ALLOW",rows.size());return Map.of("decision","ALLOW","results",rows,"aclVersion",revision,"cacheHit",ids!=null);
    }
    public Object children(UUID t,UUID w,StitchContracts.Retrieve x,Authentication auth){var p=scope(t,w);var c=caller(t,w,auth,x.sessionId(),p);var all=resources(p);var acl=grants(p);if(!StitchAccess.permits(x.resourceId(),"READ",c.human(),c.groups(),c.ai(),all,acl)){audit(p,c.subject(),"children",x.resourceId(),"DENY",0);return Map.of("decision","DENY","results",List.of(),"aclVersion",version(p));}List<String> ids=all.values().stream().filter(r->x.resourceId().equals(r.get("parent_id"))).map(r->(String)r.get("resource_id")).filter(id->StitchAccess.permits(id,"READ",c.human(),c.groups(),c.ai(),all,acl)).sorted().toList();var rows=ids.isEmpty()?List.<Map<String,Object>>of():jdbc.queryForList("SELECT resource_id,kind,title,content,source_version FROM stitch_resources WHERE "+SCOPE+" AND resource_id IN (:ids) AND deleted=false ORDER BY resource_id LIMIT 100",new MapSqlParameterSource(p.getValues()).addValue("ids",ids));stillValid(t,w,auth,c,p);rows=rows.stream().filter(r->StitchAccess.permits((String)r.get("resource_id"),"READ",c.human(),c.groups(),c.ai(),all,acl)).toList();disclose(p,c,rows.stream().map(r->(String)r.get("resource_id")).toList());audit(p,c.subject(),"children",x.resourceId(),"ALLOW",rows.size());return Map.of("decision","ALLOW","results",rows,"aclVersion",version(p));}
    public Object verify(UUID t,UUID w,Authentication auth){var a=identities.resolve(auth,t,w);return Map.of("subject",a.subject(),"actorType",a.type(),"connector",a.sync());}
    public Object revokeToken(UUID t,UUID w,StitchContracts.Revocation x,Authentication auth){var a=identities.connector(auth,t,w);var p=scope(t,w).addValue("jti",x.jti()).addValue("expires",Timestamp.from(x.expiresAt()));jdbc.update("INSERT INTO stitch_revoked_tokens(tenant_id,workspace_id,jti,expires_at) VALUES(:tenant,:workspace,:jti,:expires) ON CONFLICT(tenant_id,workspace_id,jti) DO UPDATE SET expires_at=GREATEST(stitch_revoked_tokens.expires_at,EXCLUDED.expires_at)",p);jdbc.update("UPDATE stitch_ai_sessions SET revoked=true WHERE "+SCOPE+" AND human_jti=:jti",p);invalidate(p);revokeDisclosures(p,"TOKEN_REVOKED");audit(p,a.subject(),"revokeToken",null,"ALLOW",0);return Map.of("revoked",x.jti());}
    public Object calls(UUID t,UUID w,Authentication auth){var a=identities.resolve(auth,t,w);var p=scope(t,w).addValue("subject",a.subject());return jdbc.queryForList("SELECT id,subject,operation,resource_id,decision,acl_version,returned_count,created_at FROM stitch_integration_audit WHERE "+SCOPE+(a.sync()?"":" AND subject=:subject")+" ORDER BY created_at DESC LIMIT 100",p);}
    private void vector(List<Double> vector){if(vector!=null&&(vector.size()>1536||vector.stream().anyMatch(v->v==null||!Double.isFinite(v)||Math.abs(v)>1000000)))throw new IllegalArgumentException("Invalid finite embedding");}
    public byte[] download(UUID t,UUID w,StitchContracts.Retrieve x,Authentication auth){var p=scope(t,w);var c=caller(t,w,auth,x.sessionId(),p);if(!StitchAccess.permits(x.resourceId(),"READ",c.human(),c.groups(),c.ai(),resources(p),grants(p))){audit(p,c.subject(),"download",x.resourceId(),"DENY",0);return null;}var rows=jdbc.queryForList("SELECT data FROM stitch_file_blobs WHERE "+SCOPE+" AND resource_id=:id",new MapSqlParameterSource(p.getValues()).addValue("id",x.resourceId()));if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"File unavailable");stillValid(t,w,auth,c,p);if(!StitchAccess.permits(x.resourceId(),"READ",c.human(),c.groups(),c.ai(),resources(p),grants(p))){audit(p,c.subject(),"download",x.resourceId(),"DENY",0);return null;}disclose(p,c,List.of(x.resourceId()));audit(p,c.subject(),"download",x.resourceId(),"ALLOW",1);return (byte[])rows.get(0).get("data");}
    private double cosine(List<Double>a,List<Double>b){double dot=0,x=0,y=0;for(int i=0;i<a.size();i++){dot+=a.get(i)*b.get(i);x+=a.get(i)*a.get(i);y+=b.get(i)*b.get(i);}return x==0||y==0?0:dot/Math.sqrt(x*y);}
    private String hash(String text){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));}catch(java.security.NoSuchAlgorithmException ex){throw new IllegalStateException(ex);}}
    private void audit(MapSqlParameterSource p,String subject,String op,String id,String decision,int count){jdbc.update("INSERT INTO stitch_integration_audit(id,tenant_id,workspace_id,subject,operation,resource_id,decision,acl_version,returned_count) VALUES(:call,:tenant,:workspace,:subject,:operation,:resource,:decision,:version,:count)",new MapSqlParameterSource(p.getValues()).addValue("call",UUID.randomUUID()).addValue("subject",subject).addValue("operation",op).addValue("resource",id).addValue("decision",decision).addValue("version",version(p)).addValue("count",count));}
    private void disclose(MapSqlParameterSource p,Caller c,List<String> ids){if(c.ai()==null)return;for(String id:ids)jdbc.update("INSERT INTO stitch_disclosures(id,tenant_id,workspace_id,resource_id,ai_subject,session_id,acl_version,expires_at) SELECT :receipt,:tenant,:workspace,:resource,:ai,:session,acl_version,now()+receipt_ttl_days*interval '1 day' FROM stitch_integration_scopes WHERE "+SCOPE,new MapSqlParameterSource(p.getValues()).addValue("receipt",UUID.randomUUID()).addValue("resource",id).addValue("ai",c.ai()).addValue("session",c.session()));}
    private void revokeDisclosures(MapSqlParameterSource p,String reason){
        // Conservative invalidation: all previously disclosed resources in the workspace.
        var rows=jdbc.queryForList("SELECT DISTINCT resource_id,ai_subject FROM stitch_disclosures WHERE "+SCOPE+" AND revoked=false",p);for(var r:rows)jdbc.update("INSERT INTO stitch_deletion_events(id,tenant_id,workspace_id,resource_id,target_subject,reason) VALUES(:event,:tenant,:workspace,:resource,:target,:reason)",new MapSqlParameterSource(p.getValues()).addValue("event",UUID.randomUUID()).addValue("resource",r.get("resource_id")).addValue("target",r.get("ai_subject")).addValue("reason",reason));jdbc.update("UPDATE stitch_disclosures SET revoked=true WHERE "+SCOPE,p);
    }
    public Object delete(UUID t,UUID w,String id,Authentication auth){var a=identities.connector(auth,t,w);var p=scope(t,w);var all=resources(p);if(!all.containsKey(id))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Resource unavailable");if(Boolean.TRUE.equals(all.get(id).get("deleted")))return Map.of("deletedResources",0,"externalDeletion","Inspect existing deletion events");Set<String> ids=new HashSet<>();ids.add(id);boolean changed;do{changed=false;for(var r:all.values())if(ids.contains(r.get("parent_id"))&&ids.add((String)r.get("resource_id")))changed=true;}while(changed);p.addValue("ids",ids);jdbc.update("DELETE FROM stitch_file_blobs WHERE "+SCOPE+" AND resource_id IN (:ids)",p);jdbc.update("DELETE FROM stitch_rag_chunks WHERE "+SCOPE+" AND resource_id IN (:ids)",p);jdbc.update("DELETE FROM stitch_resource_acl WHERE "+SCOPE+" AND resource_id IN (:ids)",p);jdbc.update("UPDATE stitch_resources SET deleted=true,content='',title='Deleted resource',source_version=source_version+1 WHERE "+SCOPE+" AND resource_id IN (:ids)",p);invalidate(p);sourceDirty(p);revokeDisclosures(p,"RESOURCE_DELETED");audit(p,a.subject(),"delete",id,"ALLOW",0);return Map.of("deletedResources",ids.size(),"externalDeletion","Pending connector acknowledgments; previous AI outputs cannot be recalled");}
    public Object events(UUID t,UUID w,Authentication auth){var a=identities.resolve(auth,t,w);var p=scope(t,w).addValue("subject",a.subject());if(!a.sync()&&!"AI_AGENT".equals(a.type()))throw new AccessDeniedException("Connector or recipient AI required");return jdbc.queryForList("SELECT id,resource_id,target_subject,reason,status,created_at FROM stitch_deletion_events WHERE "+SCOPE+" AND status='PENDING'"+(a.sync()?"":" AND target_subject=:subject")+" ORDER BY created_at LIMIT 100",p);}
    public Object ack(UUID t,UUID w,UUID id,String receipt,Authentication auth){var a=identities.resolve(auth,t,w);var p=scope(t,w).addValue("event",id).addValue("subject",a.subject()).addValue("receipt",receipt);if(!a.sync()&&!"AI_AGENT".equals(a.type()))throw new AccessDeniedException("Connector or recipient AI required");if(jdbc.update("UPDATE stitch_deletion_events SET status='ACKNOWLEDGED',receipt_id=:receipt,acknowledged_at=now() WHERE "+SCOPE+" AND id=:event"+(a.sync()?"":" AND target_subject=:subject"),p)==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Event unavailable");return Map.of("eventId",id,"status","ACKNOWLEDGED","meaning","Recipient statement, not proof of third-party physical erasure");}
    public Object retention(UUID t,UUID w,int days,Authentication auth){identities.connector(auth,t,w);if(days<1||days>365)throw new IllegalArgumentException("Retention range 1..365 days");var p=scope(t,w).addValue("days",days);jdbc.update("UPDATE stitch_integration_scopes SET receipt_ttl_days=:days WHERE "+SCOPE,p);jdbc.update("UPDATE stitch_disclosures SET expires_at=LEAST(expires_at,created_at+:days*interval '1 day') WHERE "+SCOPE,p);return Map.of("receiptTtlDays",days,"maintenanceRequired",true);}
    public Object maintenance(UUID t,UUID w,Authentication auth){identities.connector(auth,t,w);var p=scope(t,w);var expired=jdbc.queryForList("SELECT resource_id FROM stitch_resources WHERE "+SCOPE+" AND purge_after<=now() AND deleted=false",p);for(var r:expired)delete(t,w,(String)r.get("resource_id"),auth);jdbc.update("DELETE FROM stitch_retrieval_cache WHERE "+SCOPE+" AND expires_at<=now()",p);var receipts=jdbc.queryForList("SELECT DISTINCT resource_id,ai_subject FROM stitch_disclosures WHERE "+SCOPE+" AND expires_at<=now() AND revoked=false",p);for(var r:receipts)jdbc.update("INSERT INTO stitch_deletion_events(id,tenant_id,workspace_id,resource_id,target_subject,reason) VALUES(:event,:tenant,:workspace,:resource,:target,'RETENTION_EXPIRED')",new MapSqlParameterSource(p.getValues()).addValue("event",UUID.randomUUID()).addValue("resource",r.get("resource_id")).addValue("target",r.get("ai_subject")));int removed=jdbc.update("DELETE FROM stitch_disclosures WHERE "+SCOPE+" AND expires_at<=now()",p);jdbc.update("DELETE FROM stitch_ai_sessions WHERE "+SCOPE+" AND (expires_at<=now() OR revoked=true)",p);jdbc.update("DELETE FROM stitch_revoked_tokens WHERE "+SCOPE+" AND expires_at<=now()",p);jdbc.update("DELETE FROM stitch_integration_audit WHERE "+SCOPE+" AND created_at<now()-interval '30 days'",p);jdbc.update("DELETE FROM stitch_deletion_events WHERE "+SCOPE+" AND status='ACKNOWLEDGED' AND acknowledged_at<now()-interval '30 days'",p);return Map.of("expiredResources",expired.size(),"expiredReceiptsRemoved",removed,"externalDeletion","Inspect pending events; acknowledgments must come from recipients");}
    public Object mcp(UUID t,UUID w,JsonNode rpc,UUID delegation,Authentication auth){
        identities.resolve(auth,t,w);if(rpc==null||!rpc.isObject())throw new IllegalArgumentException("JSON object required");JsonNode id=rpc.get("id");if(!"2.0".equals(rpc.path("jsonrpc").asText())||id==null||(!(id.isTextual()||id.isIntegralNumber())||id.isTextual()&&id.asText().length()>512))throw new IllegalArgumentException("JSON-RPC id required");String method=rpc.path("method").asText();Object result;
        if("initialize".equals(method))result=Map.of("protocolVersion","2025-06-18","capabilities",Map.of("tools",Map.of()),"serverInfo",Map.of("name","zt-stitch-retrieval-adapter","version","1.0"));
        else if("tools/list".equals(method))result=Map.of("tools",List.of(Map.of("name","readDocument","description","Read an ACL-authorized resource","inputSchema",Map.of("type","object","properties",Map.of("resourceId",Map.of("type","string")),"required",List.of("resourceId"),"additionalProperties",false)),Map.of("name","searchDocuments","description","Search only authorized RAG chunks","inputSchema",Map.of("type","object","properties",Map.of("query",Map.of("type","string")),"required",List.of("query"),"additionalProperties",false)),Map.of("name","listChannelMessages","description","List authorized channel messages or folder/file children","inputSchema",Map.of("type","object","properties",Map.of("resourceId",Map.of("type","string")),"required",List.of("resourceId"),"additionalProperties",false))));
        else if("tools/call".equals(method)){var params=rpc.path("params");var args=params.path("arguments");if(!params.isObject()||!args.isObject())throw new IllegalArgumentException("Object arguments required");args.fieldNames().forEachRemaining(key->{if(!List.of("resourceId","query").contains(key))throw new IllegalArgumentException("Unknown retrieval argument");});UUID session=delegation;String name=params.path("name").asText();Object data;if("readDocument".equals(name)){String resource=args.path("resourceId").asText();if(resource.isBlank()||resource.length()>128)throw new IllegalArgumentException("Resource ID required");data=retrieve(t,w,new StitchContracts.Retrieve(resource,session),auth);}else if("listChannelMessages".equals(name)){String resource=args.path("resourceId").asText();if(resource.isBlank()||resource.length()>128)throw new IllegalArgumentException("Resource ID required");data=children(t,w,new StitchContracts.Retrieve(resource,session),auth);}else if("searchDocuments".equals(name)){String query=args.path("query").asText();if(query.isBlank()||query.length()>256)throw new IllegalArgumentException("Query required");data=search(t,w,new StitchContracts.Search(query,session,null),auth);}else throw new IllegalArgumentException("Unsupported retrieval tool");result=Map.of("content",List.of(Map.of("type","text","text",json(data))),"isError","DENY".equals(((Map<?,?>)data).get("decision")));}
        else if("ping".equals(method))result=Map.of();else throw new IllegalArgumentException("Unsupported MCP method");return Map.of("jsonrpc","2.0","id",id,"result",result);
    }
}
