apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-api
  namespace: zt-security
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxUnavailable: 0, maxSurge: 1}
  selector: {matchLabels: {app: authorization-api}}
  template:
    metadata: {labels: {app: authorization-api}}
    spec:
      serviceAccountName: authorization-api
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: authorization-api
          image: zt-security/authorization-api:local
          imagePullPolicy: IfNotPresent
          ports: [{name: http, containerPort: 8080}]
          envFrom:
            - configMapRef: {name: zt-security-config}
            - secretRef: {name: zt-security-secrets}
          resources:
            requests: {cpu: 250m, memory: 512Mi}
            limits: {cpu: "2", memory: 2Gi}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          readinessProbe: {httpGet: {path: /actuator/health/readiness, port: http}, initialDelaySeconds: 20, periodSeconds: 10}
          livenessProbe: {httpGet: {path: /actuator/health/liveness, port: http}, initialDelaySeconds: 40, periodSeconds: 20}
          startupProbe: {httpGet: {path: /actuator/health/liveness, port: http}, periodSeconds: 5, failureThreshold: 60}
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
      volumes:
        - name: tmp
          emptyDir: {sizeLimit: 256Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-api
  namespace: zt-security
spec:
  selector: {app: authorization-api}
  ports: [{name: http, port: 8080, targetPort: http}]
