import React from 'react';
import AgentConnections from '../components/AgentConnections';
import {apiGet,apiPost,WORKSPACE} from '../api/client';
export default function ProductOperations(){
 const [clients,setClients]=React.useState<any[]>([]),[settings,setSettings]=React.useState<any>(null),[identities,setIdentities]=React.useState<any[]>([]),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[clientId,setClientId]=React.useState(''),[name,setName]=React.useState(''),[secret,setSecret]=React.useState(''),[message,setMessage]=React.useState('');
 const load=React.useCallback(async()=>{setBusy(true);setError('');const r=await Promise.allSettled([apiGet('/v1/clients'),apiGet('/v1/settings'),apiGet('/v1/identities')]);setClients(r[0].status==='fulfilled'?r[0].value:[]);setSettings(r[1].status==='fulfilled'?r[1].value:null);setIdentities(r[2].status==='fulfilled'?r[2].value:[]);if(r.some(x=>x.status==='rejected'))setError(r.filter(x=>x.status==='rejected').map(x=>(x as PromiseRejectedResult).reason.message).join(' · '));setBusy(false);},[]);
 React.useEffect(()=>{void load();window.addEventListener('zt-refresh',load);return()=>window.removeEventListener('zt-refresh',load)},[load]);
 const create=async()=>{setBusy(true);setError('');setSecret('');try{const x=await apiPost('/v1/clients',{clientId:clientId.trim(),name:name.trim(),workspaceId:WORKSPACE,scopes:[]});setSecret(x.secret);setMessage('Client registered. Copy its secret now and set ZT_ORDER_AGENT_SECRET in the AI Client IDE run configuration.');await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const createAgent=async()=>{setBusy(true);setError('');try{await apiPost('/v1/identities',{externalId:clientId.trim(),type:'AI_AGENT',name:name.trim(),attributes:{}});setMessage('AI-agent identity registered. This does not create a service credential or allow policy.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <div><h2>Product Operations</h2><p>Service credentials and registered AI-agent identities are separate. Registration does not authorize tool execution.</p>{error&&<div className="error-banner" role="alert">{error}</div>}{message&&<p role="status">{message}</p>}<p>Security mode: <strong>{settings?.securityMode||'Unavailable'}</strong></p>
 <section className="panel"><h3>Register client / agent</h3><label>External ID / Client ID<input value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="order-ai-client"/></label><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Order AI Client"/></label><div className="button-row"><button disabled={busy||!clientId.trim()||!name.trim()} onClick={create}>Create service client</button><button disabled={busy||!clientId.trim()||!name.trim()} onClick={createAgent}>Create AI-agent identity</button></div>
 {secret&&<div><p>One-time secret. Store securely; it cannot be retrieved later.</p><input type="password" readOnly value={secret} aria-label="One-time secret"/><button onClick={async()=>{try{await navigator.clipboard.writeText(secret);setMessage('Secret copied. Configure it in the IDE environment; never share it.')}catch{setError('Clipboard unavailable. Select and copy the secret manually.')}}}>Copy secret</button><button onClick={()=>setSecret('')}>Dismiss secret</button></div>}</section>
 <section className="panel"><h3>Service clients</h3><button disabled={busy} onClick={load}>Refresh</button><table><thead><tr><th>Name</th><th>Caller subject</th><th>Status</th><th>Workspace</th></tr></thead><tbody>{clients.map(x=><tr key={x.id}><td>{x.name}</td><td>client:{x.clientId}</td><td>{x.status}</td><td>{x.workspaceId||'Tenant scope'}</td></tr>)}</tbody></table>{!busy&&!clients.length&&!error&&<p>No clients registered.</p>}</section>
 <AgentConnections/>
 <section className="panel"><h3>AI-agent identities</h3>{identities.filter(x=>x.identityType==='AI_AGENT').map(x=><p key={x.id}>{x.name} · {x.externalId}</p>)}</section></div>;
}
