import React from 'react';
import {apiGet,apiPost} from '../api/client';
import RetrievalClientConsole from '../components/RetrievalClientConsole';
import {notifyAction} from '../components/ActionFeedback';

type Connection={connection_id:string;display_name:string;connector_subject:string;enabled:boolean};
type Resource={resource_id:string;parent_id:string|null;kind:string;title:string};
type Policy={id:string;name:string;status:string;version:number;workspaceId:string|null;policyText:string};
const ROOT='/v1/retrieval/connections';
const ACTIONS='["retrieval.read", "retrieval.search", "retrieval.list", "retrieval.download"]';
export default function RetrievalAccess(){
 const [workspaces,setWorkspaces]=React.useState<any[]>([]),[workspace,setWorkspace]=React.useState(''),[newWorkspace,setNewWorkspace]=React.useState(''),[workspaceSlug,setWorkspaceSlug]=React.useState('');
 const [connection,setConnection]=React.useState<Connection|null>(null),[resources,setResources]=React.useState<Resource[]>([]),[policies,setPolicies]=React.useState<Policy[]>([]);
 const [connectionId,setConnectionId]=React.useState(''),[displayName,setDisplayName]=React.useState(''),[connectorSubject,setConnectorSubject]=React.useState(''),[enabled,setEnabled]=React.useState(true);
 const [effect,setEffect]=React.useState(''),[target,setTarget]=React.useState(''),[subject,setSubject]=React.useState(''),[name,setName]=React.useState(''),[draft,setDraft]=React.useState<Policy|null>(null);
 const [message,setMessageState]=React.useState(''),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[history,setHistory]=React.useState<any>(null);
 const headers={'X-Workspace-Id':workspace};
 React.useEffect(()=>{apiGet('/v1/workspaces').then(setWorkspaces).catch(e=>setError(e.message))},[]);
 const load=async(w:string)=>{const h={'X-Workspace-Id':w};const rows=await apiGet(ROOT,h);const current=rows[0]||null;setConnection(current);setConnectionId(current?.connection_id||'');setDisplayName(current?.display_name||'');setConnectorSubject(current?.connector_subject||'');setEnabled(current?.enabled??true);setResources(await apiGet(ROOT+'/resources',h));const all=await apiGet('/v1/policies/all',h);setPolicies(all.filter((p:Policy)=>(!p.workspaceId||p.workspaceId===w)&&p.policyText?.includes('retrieval.')))};
 const actionLabel=React.useRef(''),inFlight=React.useRef(false),messageRef=React.useRef('');
 const setMessage=(value:string)=>{messageRef.current=value;setMessageState(value)};
 const task=async(fn:()=>Promise<void>,label?:string)=>{if(inFlight.current)return;inFlight.current=true;const title=label||actionLabel.current||'요청';setBusy(true);setError('');setMessage('');notifyAction('running',title+' 실행 중…');try{await fn();const completed=messageRef.current||title+' 완료';setMessage(completed);notifyAction('success',completed)}catch(e:any){const detail=e.message||String(e);setError(detail);notifyAction(messageRef.current?'warning':'error',messageRef.current?messageRef.current+' · 후속 새로고침/처리 실패: '+detail:title+' 실패: '+detail)}finally{inFlight.current=false;setBusy(false)}};
 const choose=(w:string)=>{setWorkspace(w);setConnection(null);setResources([]);setPolicies([]);setDraft(null);setTarget('');setHistory(null);setConnectionId('');setDisplayName('');setConnectorSubject('');if(w)task(()=>load(w),'워크스페이스 불러오기')};
 const resetDraft=()=>setDraft(null);
 const policyText=React.useMemo(()=>{
  if(!connection||!effect||!name.trim())return '';
  const conditions=[`context.connectionId == ${JSON.stringify(connection.connection_id)}`];
  if(target)conditions.push(`resource.ancestors contains ${JSON.stringify(target)}`);
  if(subject.trim())conditions.push(`principal.id == ${JSON.stringify(subject.trim())}`);
  return `policy ${JSON.stringify(name.trim())} {\n  priority ${effect==='deny'?10:100}\n  effect ${effect}\n  principal.type == "AI_AGENT"\n  action in ${ACTIONS}\n  resource.type == "retrieval_resource"\n  condition {\n    ${conditions.join(' and\n    ')}\n  }\n}`;
 },[connection,effect,name,target,subject]);
 const save=()=>task(async()=>{if(!policyText)return;const validation=await apiPost('/v1/policies/validate',{policyText},headers);if(!validation.valid)throw Error(validation.error||'Policy validation failed');const existing=await apiGet('/v1/policies/all',headers);const version=1+Math.max(0,...existing.filter((p:Policy)=>p.name===name.trim()).map((p:Policy)=>p.version));const created=await apiPost('/v1/policies',{name:name.trim(),version,status:'DRAFT',policyText},headers);setDraft(created);setMessage('DRAFT saved in ZT. Review the DSL, then Publish.');await load(workspace)});
 const publish=()=>task(async()=>{if(!draft)return;await apiPost('/v1/policies/'+draft.id+'/publish',{},headers);setDraft(null);setMessage('Published. New AI reads/searches/downloads use this ZT policy.');await load(workspace)});
 return <div aria-busy={busy} onClickCapture={e=>{const button=(e.target as HTMLElement).closest("button");if(button&&!button.disabled)actionLabel.current=button.textContent?.trim()||"요청"}}><h2>Retrieval Access — ZT Control Plane</h2><p>Register any client’s source connector and manage AI retrieval policies centrally. Stitch is one client; this screen does not contain client-specific authorization rules.</p>{error&&<div className="error-banner" role="alert">{error}</div>}{message&&<p role="status">{message}</p>}
 <section className="panel"><h3>1. Select an isolated client workspace</h3><label>Workspace<select disabled={busy} value={workspace} onChange={e=>choose(e.target.value)}><option value="">Select workspace</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name} — {w.id}</option>)}</select></label><label>Create another client workspace<input disabled={busy} value={newWorkspace} onChange={e=>setNewWorkspace(e.target.value)} placeholder="e.g. Acme demo"/></label><label>Workspace slug<input disabled={busy} value={workspaceSlug} onChange={e=>setWorkspaceSlug(e.target.value)} placeholder="acme-demo (lowercase letters, digits, hyphens)"/></label><button disabled={busy||!newWorkspace.trim()||!workspaceSlug.trim()} onClick={()=>task(async()=>{const w=await apiPost('/v1/workspaces',{name:newWorkspace.trim(),slug:workspaceSlug.trim(),status:'ACTIVE'});setMessage('워크스페이스 '+w.name+' 등록 완료');setWorkspaces(await apiGet('/v1/workspaces'));setWorkspace(w.id);setNewWorkspace('');setWorkspaceSlug('');setDraft(null);setTarget('');setHistory(null);await load(w.id)})}>Create workspace</button><p>One source connection per workspace. Use a new workspace for the next client; its source tokens and AI credentials must carry that workspace scope.</p></section>
 <div className="grid-2"><section className="panel"><h3>2. Register the source connector</h3><label>Connection ID<input disabled={busy||!!connection} value={connectionId} onChange={e=>setConnectionId(e.target.value)} placeholder="stitch / acme / another-client"/></label><label>Display name<input disabled={busy} value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>Authenticated connector subject<input disabled={busy||!!connection} value={connectorSubject} onChange={e=>setConnectorSubject(e.target.value)} placeholder="Exact verified OIDC sub"/></label><label className="retrieval-enabled-checkbox"><input type="checkbox" disabled={busy} checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>Enabled</span></label><button disabled={busy||!workspace||!connectionId.trim()||!displayName.trim()||!connectorSubject.trim()} onClick={()=>task(async()=>{await apiPost(ROOT,{connectionId:connectionId.trim(),displayName:displayName.trim(),connectorSubject:connectorSubject.trim(),enabled},headers);setMessage(enabled?'Connection saved in ZT · Enabled':'Connection saved in ZT · Disabled');await load(workspace);setDraft(null)})}>Save connection</button><p>The source may sync user/group ACLs, content and changes. It cannot publish AI policies. Existing workspace content cannot be reassigned to another connector.</p><p>Stitch demo: <a href="http://localhost:8766" target="_blank" rel="noopener noreferrer">open client simulator</a>, click “Show ZT connection details” and copy its connectorSubject here.</p></section>
 <section className="panel"><h3>3. Author AI policies in ZT</h3><label>Policy name<input disabled={busy} value={name} onChange={e=>{setName(e.target.value);resetDraft()}} placeholder="e.g. allow_stitch_retrieval"/></label><label>Effect<select disabled={busy} value={effect} onChange={e=>{setEffect(e.target.value);resetDraft()}}><option value="">Select effect</option><option value="allow">ALLOW — still requires human ACL + delegation</option><option value="deny">DENY — overrides matching ALLOW</option></select></label><label>Resource subtree<select disabled={busy} value={target} onChange={e=>{setTarget(e.target.value);resetDraft()}}><option value="">All resources in this connection</option>{resources.map(r=><option key={r.resource_id} value={r.resource_id}>{r.kind} · {r.title} · {r.resource_id}</option>)}</select></label><label>Optional AI subject filter<input disabled={busy} value={subject} onChange={e=>{setSubject(e.target.value);resetDraft()}} placeholder="Blank = all authenticated delegated AI callers"/></label><pre className="json">{policyText||'Choose a connection, policy name and effect.'}</pre><button disabled={busy||!workspace||!policyText} onClick={save}>Validate → Save DRAFT</button><button className="primary" title={!draft?"먼저 Validate → Save DRAFT를 실행하세요.":"검토한 DRAFT 정책을 활성화합니다."} disabled={busy||!draft} onClick={publish}>Publish reviewed DRAFT</button>{draft&&<p>DRAFT: {draft.name} v{draft.version}</p>}<p>No matching ALLOW means no AI content access. A subtree rule covers files, messages and attachments through server-derived ancestors. Full DSL editing is available in Policy Studio. STEP_UP is fail closed here; this retrieval adapter has no approval-resume flow.</p></section></div>
 <section className="panel"><h3>Published and draft ZT retrieval policies</h3><button disabled={busy||!workspace} onClick={()=>task(()=>load(workspace))}>Refresh resources / policies</button>{policies.map(p=><div key={p.id} className="panel"><strong>{p.name} v{p.version} · {p.status}</strong><details><summary>Policy DSL</summary><pre className="json">{p.policyText}</pre></details>{p.status==='ACTIVE'&&<button disabled={busy||!p.workspaceId} onClick={()=>task(async()=>{await apiPost('/v1/policies/'+p.id+'/deactivate',{},headers);setMessage('Policy deactivated in ZT. Other matching policies still apply.');await load(workspace)})}>Deactivate</button>}</div>)}<p>To lift a DENY rule, deactivate that rule. Adding another ALLOW cannot override it. Tenant-wide policies are reviewed in Policy Studio.</p></section>
 <section className="panel"><h3>Actual ZT retrieval audit</h3><button disabled={busy||!workspace} onClick={()=>task(async()=>setHistory(await apiGet('/v1/retrieval/audit',headers)))}>Load calls / decisions / matched policies</button>{history&&<pre className="json">{JSON.stringify(history,null,2)}</pre>}<p>Use the client simulator to request content. Policies stay here in ZT; simulation reset and source sync do not reset them.</p></section>
 <RetrievalClientConsole key={workspace} workspace={workspace}/>
 </div>;
}



