import React from 'react';
import {apiGet,apiPost,apiPut,mcpRequest,McpCredentials} from '../api/client';
import usePageRefresh from '../components/usePageRefresh';

export default function StitchAccessPoc(){
 const [catalog,setCatalog]=React.useState<any>(null),[calls,setCalls]=React.useState<any[]>([]),[identity,setIdentity]=React.useState<any>(null),[result,setResult]=React.useState<any>(null);
 const [auth,setAuth]=React.useState<McpCredentials>({mode:'default'}),[draft,setDraft]=React.useState<McpCredentials>({mode:'default'});
 const [operation,setOperation]=React.useState(''),[resource,setResource]=React.useState(''),[query,setQuery]=React.useState('payroll'),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState('');
 const [settingsActor,setSettingsActor]=React.useState<any>(null);const ticket=React.useRef(0);
 const load=async()=>{const n=++ticket.current;setBusy(true);setError('');try{
   const settings=await apiGet('/v1/poc/stitch/context');if(n!==ticket.current)return;setSettingsActor(settings);
   const [c,i,h]=await Promise.all([settings.canManage?apiGet('/v1/poc/stitch/management'):Promise.resolve(null),mcpRequest('/v1/poc/stitch/context','GET',undefined,auth),mcpRequest('/v1/poc/stitch/calls','GET',undefined,auth)]);
   if(n!==ticket.current)return;setCatalog(c);setIdentity(i);setCalls(h);
 }catch(e:any){if(n===ticket.current){setIdentity(null);setCatalog(null);setCalls([]);setError(e.message)}}finally{if(n===ticket.current)setBusy(false)}};
 usePageRefresh(load);React.useEffect(()=>{setResult(null);setResource('');setIdentity(null);void load();return()=>{ticket.current++}},[auth]);
 const action=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setMessage('');try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const setup=()=>action(async()=>{await apiPost('/v1/poc/stitch/setup',{});await load();setMessage('Synthetic fixtures ready. Existing access settings are preserved. No customer data was loaded.');});
 const configure=(id:string,access:string)=>action(async()=>{await apiPut('/v1/poc/stitch/areas/'+encodeURIComponent(id)+'/access',{agentAccess:access});setResult(null);await load();setMessage('Access setting saved. Parent DENY takes precedence over child ALLOW.');});
 const execute=()=>action(async()=>{setResult(null);const body=operation==='readDocument'?{documentId:resource}:operation==='listChannelMessages'?{channelId:resource}:{query};const response=await mcpRequest('/v1/poc/stitch/'+operation,'POST',body,auth);await load();setResult(response);});
 const documents=catalog?.documents||[],channels=(catalog?.areas||[]).filter((x:any)=>x.kind==='CHANNEL');
 return <div><div className="page-header"><div><h2>Stitch AI Access PoC</h2><p>Synthetic folder/channel access demo. Actual Stitch integration, RAG and TEE are outside this PoC.</p></div><button disabled={busy} onClick={load}>Refresh</button></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}{message&&<p role="status">{message}</p>}
 <section className="panel"><h3>1. Synthetic resource settings</h3><p>This catalog uses the configured administrator credential: <strong>{settingsActor?.subject||'Unavailable'}</strong>. Titles here are administrator metadata, not AI retrieval results.</p>
 {settingsActor?.canManage&&<button disabled={busy} onClick={setup}>Initialize synthetic fixtures</button>}
 <table><thead><tr><th>Area</th><th>Kind</th><th>Parent</th><th>Local AI access</th><th>Effective AI access</th></tr></thead><tbody>{(catalog?.areas||[]).map((x:any)=><tr key={x.area_id}><td>{x.name}<br/><code>{x.area_id}</code></td><td>{x.kind}</td><td>{x.parent_id||'—'}</td><td><select disabled={busy||!settingsActor?.canManage} value={x.agent_access} onChange={e=>configure(x.area_id,e.target.value)}><option>ALLOW</option><option>DENY</option></select></td><td>{x.effectiveAgentAccess}</td></tr>)}</tbody></table>
 {!catalog?.areas?.length&&<p>Initialize fixtures as an administrator. Default Payroll and Payroll channel deny AI access; Payroll archive inherits its parent restriction.</p>}</section>
 <div className="grid-2"><section className="panel"><h3>2. Authenticated retrieval caller</h3><p>Select authentication, not a simulated principal. The server ignores client-supplied resource access settings.</p>
 <label>Credential<select disabled={busy} value={draft.mode} onChange={e=>setDraft({mode:e.target.value as McpCredentials['mode']})}><option value="default">Configured administrator — human demo access</option><option value="service">Registered AI service client</option><option value="bearer">OIDC JWT — trusted actor_type claim</option></select></label>
 {draft.mode==='service'&&<label>Client ID<input disabled={busy} value={draft.clientId||''} onChange={e=>setDraft({...draft,clientId:e.target.value})} placeholder="order-ai-client"/></label>}
 {draft.mode!=='default'&&<label>{draft.mode==='bearer'?'Bearer token':'Client secret'}<input disabled={busy} type="password" autoComplete="off" value={draft.secret||''} onChange={e=>setDraft({...draft,secret:e.target.value})}/></label>}
 <button disabled={busy} onClick={()=>{if(draft.mode!=='default'&&(!draft.secret?.trim()||draft.mode==='service'&&!draft.clientId?.trim())){setError('Client ID and credential required');return}setAuth({...draft});setDraft({...draft,secret:''});setResult(null)}}>Apply identity</button>
 <p>Authenticated subject: <strong>{identity?.subject||'Unavailable'}</strong> · Actor: <strong>{identity?.actorType||'—'}</strong></p><p>{identity?.humanMode}</p>
 <label>Operation<select disabled={busy} value={operation} onChange={e=>{setOperation(e.target.value);setResource('');setResult(null)}}><option value="">Select operation</option><option value="readDocument">readDocument</option><option value="searchDocuments">searchDocuments</option><option value="listChannelMessages">listChannelMessages</option></select></label>
 {operation==='searchDocuments'?<label>Search text<input disabled={busy} value={query} onChange={e=>{setQuery(e.target.value);setResult(null)}} maxLength={100}/></label>:operation&&<label>{operation==='readDocument'?'Document ID':'Channel ID'}<select disabled={busy} value={resource} onChange={e=>{setResource(e.target.value);setResult(null)}}><option value="">Select synthetic resource</option>{(operation==='readDocument'?documents:channels).map((x:any)=><option key={x.document_id||x.area_id} value={x.document_id||x.area_id}>{x.title||x.name} · {x.document_id||x.area_id}</option>)}</select>{!catalog&&<input value={resource} onChange={e=>{setResource(e.target.value);setResult(null)}} placeholder="Known resource ID"/>}</label>}
 <button className="primary" disabled={busy||!identity||!operation||(operation==='searchDocuments'?!query.trim():!resource)} onClick={execute}>Execute governed retrieval</button></section>
 <section className="panel"><h3>3. Retrieval result</h3>{result?<><p>Decision: <strong>{result.decision}</strong> · Caller: {result.subject}</p><p>{result.reason}</p><p>Returned content rows: {result.contentReads} · Call ID: {result.callId}</p><pre className="json">{JSON.stringify(result,null,2)}</pre></>:<p>Select a caller and operation. A denied direct read returns no content rows. Search returns only authorized documents.</p>}<p>contentReads measures rows returned to this application by its permitted content retrieval queries; it is not an external invocation counter or a database physical-read measurement.</p></section></div>
 <section className="panel"><h3>4. PoC call history</h3><p>Scoped synthetic PoC records, separate from MCP/workflow history. AI callers see their own calls; administrators see the workspace. Search text and document content are not stored in this history.</p><table><thead><tr><th>Time</th><th>Caller</th><th>Operation</th><th>Resource</th><th>Decision</th><th>Content rows</th></tr></thead><tbody>{calls.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.subject}<br/>{x.actor_type}</td><td>{x.operation}</td><td>{x.resource_id||'—'}</td><td>{x.decision}</td><td>{x.content_reads}</td></tr>)}</tbody></table>{!calls.length&&<p>No PoC calls for this caller.</p>}</section>
 </div>;
}
