apiVersion: v1
kind: ServiceAccount
metadata:
  name: zt-policy-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zt-policy-operator
rules:
  - apiGroups: [security.zt-platform.io]
    resources: [zerotrustpolicies]
    verbs: [get, list, watch]
  - apiGroups: [security.zt-platform.io]
    resources: [zerotrustpolicies/status]
    verbs: [get, patch, update]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zt-policy-operator
subjects:
  - kind: ServiceAccount
    name: zt-policy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zt-policy-operator
